### ISSUE TITLE
Install script ends without errors but i cant run application from anywhere

### ISSUE THREAD

**Issue by hellofaduck** [Lifailon/lazyjournal#3]
I can run program by typing  $HOME/.local/bin/lazyjournal but
`root@audiobookshelf:~# https://raw.githubusercontent.com/Lifailon/lazyjournal/main/install.sh
-bash: https://raw.githubusercontent.com/Lifailon/lazyjournal/main/install.sh: No such file or directory
root@audiobookshelf:~# curl https://raw.githubusercontent.com/Lifailon/lazyjournal/main/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1569  100  1569    0     0   5563      0 --:--:-- --:--:-- --:--:--  5563
_  Installation completed successfully
root@audiobookshelf:~# lazyjournal
lazyjournal: command not found
`
I test this on two servers with Debian based distros

**Comment by Lifailon** [comment]
Does the problem persist after rebooting the user session?

If you are using the default `bash`, check the contents of the `$HOME/.bashrc` file, there should be a line at the end of the file:
```
export PATH=$PATH:$HOME/.local/bin
```

**Comment by hellofaduck** [comment]
Yeah, line is present but not on new line, i think this is the problem
`alias bat="batcat"export PATH=$PATH:$HOME/.local/bin`

**Comment by Lifailon** [comment]
Is your output exactly in the last line? In that case it should cause errors when running the `source` command.

Check the modification date of your `.bashrc` file, to make sure when the change was made and compare it with the installation date of `lazyjournal`.

The script checks during installation, and if the line is missing, only then `export` is added for the directory on a new line.

In your case, edit the file like this:

> alias bat="batcat"export PATH=$PATH:$HOME/.local/bin

```
alias bat="batcat"
export PATH=$PATH:$HOME/.local/bin
```

**Comment by Lifailon** [comment]
Give feedback if you still have problems during installation, or I will **close this issue**.
