### ISSUE TITLE
Processor architecture not supported: arm64

### ISSUE THREAD

**Issue by kignatovich** [Lifailon/lazyjournal#5]
I can't run the project on my MacOS laptop. Will there be support for the arm64 architecture?

**Comment by Lifailon** [comment]
> Will there be support for the arm64 architecture?

Will you be able to run the project from source code? It may already be working and just need to adjust the installation process.

**Comment by Lifailon** [comment]
@kignatovich You may have had an error: `Operation not permitted`, I noticed such a problem and fixed it in the installation script to exclude the executable from quarantine, and a new release has been released, please check the installation.

**Comment by kignatovich** [comment]
@Lifailon Thank you. I'll check today.

**Comment by Lifailon** [comment]
I am closing this issue, if other issues arise please open a new request.
