### ISSUE TITLE
`btmp` (bad login attempts) starts from beginning 

### ISSUE THREAD

**Issue by Kenya-West** [Lifailon/lazyjournal#6]
First, thanks for such a good utility! I am fan of all that `lazy*` stuff, and `lazyjournal` will stay in my collection!

## The problem
 
AFAIK `btmp` is binary-formatted journal that contains bad login attempts, mostly for SSH.

`lazyjournal` displays `btmp` from start on Ubuntu 22.04, not the last records:

![image](https://github.com/user-attachments/assets/44b6fa05-dcfb-4c3e-868a-06e125bbe518)

I suggest either of ways to solve it, the best is to have all of them:
1. Implement `home`, `end`, `pgdown`, `pgup` shortcuts to navigate in log window, like in [lnav](https://github.com/tstack/lnav);
2. Allow to set order of lines somehow;
2.1. The app will remember it for this particular journal, and next time will apply previous sorting.

**Comment by Lifailon** [comment]
Thanks for the feedback!
I understand what you mean, I will change the order of reading lines from the end and add it in the next release. I also noticed that btmp creates archive logs (`btmp.1`), which are not read correctly, I will also fix this.
At the moment, I am working on coloring the log output, the update is planned for the first half of next week.

**Comment by Lifailon** [comment]
For example like this:

![image](https://github.com/user-attachments/assets/6b6875b4-b37e-4712-a7c5-4ba3d7d2b601)

**Comment by Lifailon** [comment]
@Kenya-West A new release has been released which fixes the `btmp` output. Please check.

**Comment by Kenya-West** [comment]
@Lifailon looks way cooler than before! And the bug is fixed. Thank you for response and your work in this definitely one of the most useful tools!

Some screenshots:

![image](https://github.com/user-attachments/assets/5fb7c845-7d17-451e-b93f-0393649de9fe)
![image](https://github.com/user-attachments/assets/6efccdf0-a3c2-4d48-8911-956a6712a6b9)

**Comment by Lifailon** [comment]
Thanks for your feedback!
