### ISSUE TITLE
Error "Failed to decode JSON: invalid character 'b' looking for beginning of value" on startup (Ubuntu 20.04)

### ISSUE THREAD

**Issue by ristomatti** [Lifailon/lazyjournal#7]
The app crashes on startup on my Ubuntu 20.04 based OS:

```
$ lazyjournal
2024/12/26 23:01:04 Failed to decode JSON: invalid character 'b' looking for beginning of value
```

I couldn't use the official release binary due to Ubuntu 20.04's ancient GLIBC version, so I've installed the package via `go install github.com/Lifailon/lazyjournal`. I also tried building from source as instructed on the README, but got the same result. Running with `sudo` did not make a difference either.

Also after the error, my terminal rendering breaks, e.g.

```
$ ls /dev/input      
by-id    event11  event16  event20  event25   event26   event3   event6  mouse0  mouse5
                                                                                       by-path  event12  event17  event21  event256  event260  event30  event7  mouse1  mouse6
                                                                           event0   event13  event18  event22  event257  event27   event31  event8  mouse2  mouse7
```

Running `reset` fixes this though.

**Comment by Lifailon** [comment]
When running from source code, everything works without errors?

I'll try to find out what this error might be related to and give feedback in a few days.

**Comment by Lifailon** [comment]
Ubuntu 20.04 probably does not contain `systemctl` output in `json` format.

@ristomatti please run the command and check that the output is in JSON format:

```shell
systemctl list-units --all --plain --no-legend --no-pager --output=json
```

**Comment by Lifailon** [comment]
@ristomatti, i found this bug on Ubuntu Server 20.04.6 and fixed it in the latest [commit](https://github.com/Lifailon/lazyjournal/commit/33ca0e1d63e749876c19c92aea6489a6b3064995).

The first GLIBC error was also caused by JSON parsing (after assembly everything works too). You can check it yourself by cloning the latest changes from the repository and give feedback, or wait for the release and install the binary using the script.

**Comment by ristomatti** [comment]
The output is indeed not JSON.


I tried converting it to JSON using [jc](https://github.com/kellyjonbrazil/jc), but unfortunately (for me) the end result was not 1:1. :smile:

```
systemctl list-units --all --plain --no-legend --no-pager | jc --systemctl -p | head -n 13
```

```json
[
  {
    "boot.automount": "Arbitrary Executable File Formats File System Automount Point",
    "not-found": "loaded",
    "inactive": "active",
    "dead": "running"
  },
  {
    "boot.automount": "SKHynix_HFS001TD9TNI-L2B0B 2",
    "not-found": "loaded",
    "inactive": "active",
    "dead": "plugged"
  },
```

> The first GLIBC error was also caused by JSON parsing (after assembly everything works too). You can check it yourself by cloning the latest changes from the repository and give feedback, or wait for the release and install the binary using the script.

I was already about to post "I guess I'm out of luck then" but just then re-read this. I see you have implemented parsing of the tabular output, awesome! Fix confirmed, thank you!

![image](https://github.com/user-attachments/assets/b1e8a6bc-65cc-44e5-9a73-791d7b16201a)
